# Generated by Django 2.2.5 on 2019-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/raghavdhingra/image/upload/v1574788770/img_k2mozj.png', max_length=500, null=True),
        ),
    ]
