# Generated by Django 2.2.5 on 2019-11-27 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=200, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('show', models.BooleanField(blank=True, default=True, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
